from typing import Protocol, Sequence, Any


class Controller(Protocol):
    def reset(self, seed: int | None = None) -> None: ...
    def apply(self, x: Sequence[float]) -> Any: ...
    def safe(self, x: Sequence[float]) -> bool: ...
